name: Build/release

# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the master branch
      - master

env:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10.16

      - name: Build/release Electron app
        env:
          # macOS notarization API key
          APPLEID: ${{ secrets.apple_id }}
          APPLEIDPASS: ${{ secrets.apple_id_pass }}
        uses: samuelmeuli/action-electron-builder@v1
        with:
          #Build scipt
          build_script_name: build-mainnet

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)

          github_token: ${{ secrets.github_token }}

          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
