name: Confirm E2E tests success
on:
  repository_dispatch:
    types: [comment-pr-on-success]
jobs:
  comment:
    name: Comment on PR#${{ github.event.client_payload.pr_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if result was already commented
        uses: peter-evans/find-comment@v1
          id: checkComment
          with:
            issue-number: ${{ github.event.client_payload.pr_number }}
            body-includes: E2E Tests
      - name: Create success comment
        if: ${{ github.event.client_payload.status == 'success' && steps.checkComment.outputs.comment-id == ''}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pr_number }}
          body: |
            E2E Tests Passed
            Check the results here: https://github.com/gnosis/safe-react-e2e-tests/actions/runs/${{ github.event.client_payload.run_number }}
            ${{ github.event.client_payload.message }}
      - name: Create failure comment
        if: ${{ github.event.client_payload.status == 'failure' && steps.checkComment.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pr_number }}
          body: |
            E2E Tests Failed
            Check the results here: https://github.com/gnosis/safe-react-e2e-tests/actions/runs/${{ github.event.client_payload.run_number }}
            ${{ github.event.client_payload.message }}
      - name: Edit success comment
        if: ${{ github.event.client_payload.status == 'success' && steps.checkComment.outputs.comment-id != ''}}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pr_number }}
          comment-id: ${{ steps.checkComment.outputs.comment-id }}
          body: |
            E2E Tests Passed
            Check the results here: https://github.com/gnosis/safe-react-e2e-tests/actions/runs/${{ github.event.client_payload.run_number }}
            ${{ github.event.client_payload.message }}
      - name: Edit failure comment
        if: ${{ github.event.client_payload.status == 'failure' && steps.checkComment.outputs.comment-id != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.pr_number }}
          comment-id: ${{ steps.checkComment.outputs.comment-id }}
          body: |
            E2E Tests Failed
            Check the results here: https://github.com/gnosis/safe-react-e2e-tests/actions/runs/${{ github.event.client_payload.run_number }}
            ${{ github.event.client_payload.message }}
